### ISSUE TITLE
Mouse gene models

### ISSUE THREAD

**Issue by jmfernandez** [MPIIComputationalEpigenetics/DeepBlue#158]
Querying DeepBlue I have realized it contains several mouse genomes, but no gene model linked to these ones.

Could you add them, please? I have been researching a bit. For mm9 (NCBIM37, GRCm37) the only available GENCODE release is the first one ([M1](http://www.gencodegenes.org/mouse_releases/1.html)). The other GENCODE releases are compatible with mm10 (GRCm38), so you can use either the latest one ([M13](http://www.gencodegenes.org/mouse_releases/13.html)) or the nearest one to the projects' release dates using mm10 as reference.

**Comment by felipealbrecht** [comment]
Work in progress - https://github.com/MPIIComputationalEpigenetics/DeepBlue-Populator/commit/c51cc7111e74759b2617ef639e36de61d1706320

**Comment by felipealbrecht** [comment]
Gencode vM1 and vM13 were included into DeepBlue.
