### ISSUE TITLE
Taxonomic id of each genome

### ISSUE THREAD

**Issue by jmfernandez** [MPIIComputationalEpigenetics/DeepBlue#159]
The different registered reference genomes found in DeepBlue are described in their description, but they are not currently providing the NCBI taxonomic id of the reference genome's organism. This id can be used at programmatic level to cluster different reference genome releases of the same organism, and also to generate links to external resources.

Could you add this taxonomic id to the genome in some way, (for instance, extra metadata), please?

**Comment by felipealbrecht** [comment]
The data was included into DeepBlue.
You can access the genome species and taxon_id by the info(genome_id, user_key) command.
